# Some tasks like setting up the database should only ever get run once.
- name: ensure there is a ansible directory
  file: path=/home/gitlab_ci/.ansible state=directory owner=$gitlab_ci_user group=$gitlab_ci_group

#TODO Add in postres in conditional
#sudo -u gitlab_ci -H cp config/database.yml.postgresql config/database.yml
#

- name: Set the database.yml configuration file 
  template: src=templates/home/gitlab_ci/gitlab-ci/config/database.yml.j2 dest=/home/gitlab_ci/gitlab-ci/config/database.yml owner=$gitlab_ci_user group=$gitlab_ci_group

# Note if this fails for some reason you might need to manually remove the .ansible/setup-db
- name: setup database
  shell: sudo -u gitlab_ci -H bundle exec rake db:setup RAILS_ENV=production force=yes && sudo -u gitlab_ci -H touch /home/gitlab_ci/.ansible/setup-db chdir=/home/gitlab_ci/gitlab-ci creates=/home/gitlab_ci/.ansible/setup-db

- name: Setup schedules
  shell: sudo -u gitlab_ci -H bundle exec whenever -w RAILS_ENV=production chdir=/home/gitlab_ci/gitlab-ci


