---

# Play book installs gitlab-ci
- name: clone gitlab ci source
  git: repo=https://github.com/gitlabhq/gitlab-ci.git dest=/home/gitlab_ci/gitlab-ci #version=$gitlabVersion

- name: gitlab-ci should be owned by gitlab_ci user
  file: path=/home/gitlab_ci/gitlab-ci owner=$gitlab_ci_user group=$gitlab_ci_group recurse=yes state=directory

- name: Set the application.yml configuration file
  template: src=home/gitlab_ci/gitlab-ci/config/application.yml.j2 dest=/home/gitlab_ci/gitlab-ci/config/application.yml owner=$gitlab_ci_user group=$gitlab_ci_group

- name: ensure copy of puma config exists
  template: src=home/gitlab_ci/gitlab-ci/config/puma.rb.j2 dest=/home/gitlab_ci/gitlab-ci/config/puma.rb owner=$gitlab_ci_user group=$gitlab_ci_group

- name: Create directory for sockets and make sure GitLab-ci can write to it
  file: path=/home/gitlab_ci/gitlab-ci/tmp/sockets/ state=directory owner=$gitlab_ci_user group=$gitlab_ci_group

- name: ensure GitLab-ci can write to sockets
  command: chmod -R u+rwX /home/gitlab_ci/gitlab-ci/tmp/sockets

- name: Create directory for pids and make sure GitLab-ci can write to it
  file: path=/home/gitlab_ci/gitlab-ci/tmp/pids/ state=directory owner=$gitlab_ci_user group=$gitlab_ci_group

- name: ensure GitLab-ci can write to pid
  command: chmod -R u+rwX /home/gitlab_ci/gitlab-ci/tmp/pids
