---
# Gitlab playbook

# Install bundler
- name: ensure bundler is installed
  gem: name=bundler state=present 

# Add gitlab_ci user
- name: ensure user gitlab_ci is present
# Possible problem is that --disabled-password is not set explicitly – I couldn’t find anything like that.
  user: state=present name=gitlab_ci system=yes shell=/bin/sh comment="GitLab CI" 
