---
# Gitlab playbook

- name: install mysql dependencies
  action: apt pkg=$item state=installed
  with_items:
    - mysql-server 
    - mysql-client 
    - libmysqlclient-dev
    - python-mysqldb

- name: ensure database user for gitlab_ci is present
  mysql_user: state=present name=$gitlab_ci_db_username host=localhost password=$gitlab_ci_db_password

- name: ensure database gitlab_ci_production is present
  mysql_db: state=present name=gitlab_ci_production collation=utf8_unicode_ci encoding=utf8

#TODO: Whoops, fix the databaseusername in this command
- name: ensure database user gitlab has necessary privleges
  mysql_user: state=present name=$gitlab_ci_db_username priv=gitlab_ci_production.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER
